import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { calculate } from 'count-up-down';
import { useEffect, useState } from 'react';

import styles from '../styles/Home.module.css';

const ONE_HOUR_AGO = new Date(new Date().getTime() - 3600 * 1000);

const Home: NextPage = () => {
  const [state, setState] = useState(calculate(ONE_HOUR_AGO, new Date()));

  useEffect(() => {
    function tick() {
      setState(calculate(ONE_HOUR_AGO, new Date()));
    }

    const interval = setInterval(tick, 1000);

    return () => {
      clearInterval(interval);
    };
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <div className={styles.card}>
            <div className={styles.value}>{state.result.years}</div>
            <div className={styles.unit}>years</div>
          </div>
          <div className={styles.card}>
            <div className={styles.value}>{state.result.months}</div>
            <div className={styles.unit}>months</div>
          </div>
          <div className={styles.card}>
            <div className={styles.value}>{state.result.days}</div>
            <div className={styles.unit}>days</div>
          </div>
          <div className={styles.card}>
            <div className={styles.value}>{state.result.hours}</div>
            <div className={styles.unit}>hours</div>
          </div>
          <div className={styles.card}>
            <div className={styles.value}>{state.result.minutes}</div>
            <div className={styles.unit}>minutes</div>
          </div>
          <div className={styles.card}>
            <div className={styles.value}>{state.result.seconds}</div>
            <div className={styles.unit}>seconds</div>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
